config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  resources :market_lists do
    resources :market_list_items
  end

  root to: 'market_lists#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/market_list.rb
# frozen_string_literal: true

class MarketList < ApplicationRecord
  validates :market_date, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/market_lists_controller.rb
# frozen_string_literal: true

class MarketListsController < ApplicationController
  before_action :find_market_list, only: [:show, :edit, :update]

  def index
    @market_lists = MarketList.all
  end

  def new
    @market_list = MarketList.new
  end

  def create
    # raise params.require(:market_list).permit(:name, :market_date).inspect
    @market_list = MarketList.new(params.require(:market_list).permit(:name, :market_date))

    if @market_list.save
      flash[:success] = 'Nova lista criada com Sucesso'
      redirect_to action: :index
    else
      render :new
    end
  end

  def edit; end

  def update
    @market_list.attributes = params.require(:market_list).permit(:name, :market_date)

    if @market_list.save
      flash[:success] = 'Lista editada com sucesso'
      redirect_to action: :index
    else
      render :edit
    end
  end

  def show; end

  protected

  def find_market_list
    @market_list = MarketList.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/market_lists_helper.rb
# frozen_string_literal: true

module MarketListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleMarketList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/market_lists/_form.html.erb
<%= form_for @market_list do |f| %>
  <label>Nome</label>: <%= f.text_field :name %>
  <br />
  <label>Data</label>: <%= f.date_field :market_date %>
  <br />
  <%= f.submit %>
<% end %>

app/views/market_lists/edit.html.erb
<h2>Editar Lista</h2>

<%= render 'form' %>

app/views/market_lists/index.html.erb
<% if flash[:success].present? %>
  <p><%= flash[:success] %></p>
<% end %>

<h1>Suas listas de mercado</h1>
<%= link_to 'Nova Lista de Mercado', new_market_list_path %>

<% if @market_lists.any? %>
  <table>
    <thead>
      <th>ID</th><th>Nome</th><th>Data</th>
    </thead>
    <tbody>
      <% @market_lists.each do |ml| %>
        <tr>
          <td><%= ml.id %></td>
          <td><%= ml.name %></td>
          <td><%= l ml.market_date %></td>
          <td><%= link_to 'Visualizar', market_list_path(ml) %> | <%= link_to 'Editar', edit_market_list_path(ml) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>Você ainda não possui nenhuma lista</p>
<% end %>

app/views/market_lists/new.html.erb
<h2>Nova Lista</h2>

<%= render 'form' %>

app/views/market_lists/show.html.erb
<h1><%= @market_list.name %> - <%= l @market_list.market_date %></h1>

<%= link_to 'Voltar', market_lists_path %>
<%= link_to 'Novo item', new_market_list_market_list_item_path(@market_list) %>

<p>Você ainda não possui nenhum item para essa lista</p>